# Generated by Django 5.2.6 on 2025-09-30 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['platform', 'product_id'], name='products_pr_platfor_556406_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('platform', 'product_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['created_at'], name='products_pr_created_26fe05_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['price'], name='products_pr_price_44ee62_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['rating'], name='products_pr_rating_ad0cb1_idx'),
        ),
    ]
