version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev   # switch to Dockerfile.prod for prod
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.base
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=fusionhub
      - POSTGRES_USER=fusionhub
      - POSTGRES_PASSWORD=secret

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.base
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.base
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
